<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_message_invalid_email_password</name>
   <tag></tag>
   <elementGuidId>02813091-a2c1-40f9-ab38-9f51b3c419d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='email_container']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error_message_invalid_email_password</value>
      <webElementGuid>4ad51a9e-3930-44e5-ae71-3e9a8e34ef4b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
