<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_message_invalid_email</name>
   <tag></tag>
   <elementGuidId>3bfec4ea-1eb7-4897-bf91-9c3ef63263d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='email_container']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error_message_invalid_email</value>
      <webElementGuid>d6632566-7a29-4a7e-92bf-5abec59fa99f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
