<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_with_password</name>
   <tag></tag>
   <elementGuidId>a88ad6e2-179e-4100-8806-22ff7e09ea81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a._aklt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='u_0_1_8G']/div/div[3]/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>353f811f-c418-46fa-bc31-7e2a2868362c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_aklt</value>
      <webElementGuid>bb7d21cd-b531-4cbd-a32b-e3378faa6524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login/web/?cuid=AYi7XafqHu-oi_Mrhj9wqx6vaGK17CA1kDfJK0tQeyrMzyq7yqAhTuLGNQecFPWggv56GCxPN3JYW3t4YcygB8CPEqZ3qOX5AVuuoZx_cKrX5bjftka2T4zhyKyQkjM1mNlbs_9y49cwTlUpC1htTUxjAIBNqOOvKRJTzeQPIMwPLpCDuM_6SHgn-AmahLESsfHoBGuC40ocnbZlD7l8jXSIDiPR6bo8aDpKVFWFvDaFnFDKV9OWP9onYxlFhHcA3m5k-VX6-8uZ2GjeaZIp-ibV&amp;email=syifaumker%40gmail.com&amp;is_from_lara=1</value>
      <webElementGuid>c42dc32b-4a63-4765-9e99-18af05fbeba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in with password</value>
      <webElementGuid>a7f4d84b-ecaf-4887-a290-4e18e2646110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_1_8G&quot;)/div[@class=&quot;mtl mbm ptm uiInterstitial _aklr uiInterstitialLarge uiBoxWhite&quot;]/div[@class=&quot;uiInterstitialBar _amyj uiBoxGray topborder&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;pts&quot;]/a[@class=&quot;_aklt&quot;]</value>
      <webElementGuid>9b8f23d5-36f2-4334-bf47-303758c09237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_1_8G']/div/div[3]/div/div[2]/a</value>
      <webElementGuid>73ede9a6-beaf-4dc8-9b1c-52df86ff5642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log in with password')]</value>
      <webElementGuid>c2b45f6d-652b-41b7-a36d-94efeb28551f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::a[1]</value>
      <webElementGuid>4d49fc3d-1d82-4bc1-aec1-1feba984721b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try another way'])[1]/following::a[1]</value>
      <webElementGuid>682ca290-ded3-4695-8dfe-a7d04b3c8694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::a[1]</value>
      <webElementGuid>2e9cc9a7-53c4-4442-a95e-a4713c66484a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/preceding::a[1]</value>
      <webElementGuid>353ad597-0138-4bfe-b34b-11fbfae2f3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log in with password']/parent::*</value>
      <webElementGuid>26a5a5ba-9173-48dd-b48e-240742160a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login/web/?cuid=AYi7XafqHu-oi_Mrhj9wqx6vaGK17CA1kDfJK0tQeyrMzyq7yqAhTuLGNQecFPWggv56GCxPN3JYW3t4YcygB8CPEqZ3qOX5AVuuoZx_cKrX5bjftka2T4zhyKyQkjM1mNlbs_9y49cwTlUpC1htTUxjAIBNqOOvKRJTzeQPIMwPLpCDuM_6SHgn-AmahLESsfHoBGuC40ocnbZlD7l8jXSIDiPR6bo8aDpKVFWFvDaFnFDKV9OWP9onYxlFhHcA3m5k-VX6-8uZ2GjeaZIp-ibV&amp;email=syifaumker%40gmail.com&amp;is_from_lara=1')]</value>
      <webElementGuid>8772fc49-0ebc-4b7d-9808-a074ab8a4a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>646feae3-1519-4b04-9b98-4871b2e5895a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login/web/?cuid=AYi7XafqHu-oi_Mrhj9wqx6vaGK17CA1kDfJK0tQeyrMzyq7yqAhTuLGNQecFPWggv56GCxPN3JYW3t4YcygB8CPEqZ3qOX5AVuuoZx_cKrX5bjftka2T4zhyKyQkjM1mNlbs_9y49cwTlUpC1htTUxjAIBNqOOvKRJTzeQPIMwPLpCDuM_6SHgn-AmahLESsfHoBGuC40ocnbZlD7l8jXSIDiPR6bo8aDpKVFWFvDaFnFDKV9OWP9onYxlFhHcA3m5k-VX6-8uZ2GjeaZIp-ibV&amp;email=syifaumker%40gmail.com&amp;is_from_lara=1' and (text() = 'Log in with password' or . = 'Log in with password')]</value>
      <webElementGuid>5a1753f7-f0ad-46a3-ab3e-e14995c7a6f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
