<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_password</name>
   <tag></tag>
   <elementGuidId>36d762ea-d9f2-4a68-bf03-3363cdff6294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_0_1_XX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='u_0_1_XX']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>9f1e5c54-b5fb-4585-a477-2551dd88ed28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6dbb62a2-977b-4702-a9c2-7c5d3688f534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>9aba9601-6e68-4137-bd9b-46af70244ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>/ajax/recover/initiate/?recover_method=recover_openid&amp;selected_cuid=AYjEE58Y58nlJEh3u3VOK7IVL0pQ692NxrNGXklKKUagbr85b09073kubDkQJhtPJznNLF2Lq79L3Y95NMAo7gMfXDyIf1s5DxR1dhJOXQ-BCaDyZvVnFl7IWJTIFg7lwBdJtYvClq5UtgEDYMR61jFSF24p9jEWMUXd8oMzpe2oP4BJIu4YiDOvq-2jYyhIsOzCSSBT0aEiOp6wVTNwBLBd9sTarp1mYQql7aAbPoZhMXzksfxGouAGcbQ9szaaddPhu8oJmRFYa0ase94sLvNX&amp;lara=1</value>
      <webElementGuid>18487398-623f-41fd-887d-0b1dd1e51416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_1_XX</value>
      <webElementGuid>a482bd16-d922-483e-86b2-23d392432739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Use your Google accountUse your Google accountThe password you've entered is incorrect.Quickly log in with your Google account.syifaumker@gmail.comCellive HasyeFacebook userNot you?Try another wayContinueLog in with password</value>
      <webElementGuid>411a5b2f-128e-4638-a3da-64a53c883127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_1_XX&quot;)</value>
      <webElementGuid>bd6028f5-c5bc-40d3-b741-802c0fea6d93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='u_0_1_XX']</value>
      <webElementGuid>89531d51-3318-43ca-a2c8-b4651f1817fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lara_strong_rec_screen']/div/form</value>
      <webElementGuid>9c1c1de1-d4ee-4ef0-befa-3b80872236fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>7adf482c-0f7d-44ba-95a2-fc4c4460863d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'u_0_1_XX' and (text() = concat(&quot;Use your Google accountUse your Google accountThe password you&quot; , &quot;'&quot; , &quot;ve entered is incorrect.Quickly log in with your Google account.syifaumker@gmail.comCellive HasyeFacebook userNot you?Try another wayContinueLog in with password&quot;) or . = concat(&quot;Use your Google accountUse your Google accountThe password you&quot; , &quot;'&quot; , &quot;ve entered is incorrect.Quickly log in with your Google account.syifaumker@gmail.comCellive HasyeFacebook userNot you?Try another wayContinueLog in with password&quot;))]</value>
      <webElementGuid>859cdb44-6854-4b03-8fe3-476439d081bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
